# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sgf_parser}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guoliang Cao"]
  s.date = %q{2011-11-28}
  s.description = %q{A simple SGF parser}
  s.email = %q{gcao99@gmail.com}
  s.executables = ["stm2dot", "sgf"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile",
    "TODO"
  ]
  s.files = [
    ".irbrc",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/sgf",
    "bin/stm2dot",
    "doc/sgf_state_machine.dot",
    "doc/sgf_state_machine.svg",
    "lib/sgf.rb",
    "lib/sgf/binary_file_error.rb",
    "lib/sgf/debugger.rb",
    "lib/sgf/default_event_listener.rb",
    "lib/sgf/model/constants.rb",
    "lib/sgf/model/event_listener.rb",
    "lib/sgf/model/game.rb",
    "lib/sgf/model/label.rb",
    "lib/sgf/model/node.rb",
    "lib/sgf/model/property_handler.rb",
    "lib/sgf/more/state_machine_presenter.rb",
    "lib/sgf/more/stm_dot_converter.rb",
    "lib/sgf/parse_error.rb",
    "lib/sgf/parser.rb",
    "lib/sgf/renderer.rb",
    "lib/sgf/sgf_helper.rb",
    "lib/sgf/sgf_state_machine.rb",
    "lib/sgf/state_machine.rb",
    "sgf_parser.gemspec",
    "spec/fixtures/2009-11-01-1.sgf",
    "spec/fixtures/2009-11-01-2.sgf",
    "spec/fixtures/chinese_gb.sgf",
    "spec/fixtures/chinese_utf.sgf",
    "spec/fixtures/example.sgf",
    "spec/fixtures/good.sgf",
    "spec/fixtures/good1.sgf",
    "spec/fixtures/kgs.sgf",
    "spec/fixtures/test.png",
    "spec/sgf/model/event_listener_spec.rb",
    "spec/sgf/model/game_spec.rb",
    "spec/sgf/model/node_spec.rb",
    "spec/sgf/more/state_machine_presenter_spec.rb",
    "spec/sgf/parse_error_spec.rb",
    "spec/sgf/parser_spec.rb",
    "spec/sgf/sgf_helper_spec.rb",
    "spec/sgf/sgf_state_machine_spec.rb",
    "spec/sgf/state_machine_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/gcao/discuz_robot}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{A SGF parser}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 1.3.0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 1.3.0"])
  end
end

